matrix:
  include:
    - language: node_js
      node_js:
        - node
    - language: python
      python:
        - 3.6
      install:
        - pip install -r test/.requirements.txt
      script:
        - python test/.test.py